// <auto-generated>
// Rewired Constants
// This list was generated on 7/18/2023 4:48:26 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace ShootBalls.ReConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal")]
        public const int Horizontal = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical")]
        public const int Vertical = 1;
        
        // Gameplay
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "Fire")]
        public const int Fire = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "AimHorizontal")]
        public const int AimHorizontal = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Gameplay", friendlyName = "AimVertical")]
        public const int AimVertical = 4;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
        public const int Gameplay = 1;
        
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
            
        }
        public static partial class Keyboard {
            public const int Default = 0;
            
        }
        public static partial class Mouse {
            public const int Default = 0;
            
        }
        public static partial class CustomController {
            public const int Default = 0;
            
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
